### ISSUE TITLE
Problemas con los tests

### ISSUE THREAD

**Issue by flbulgarelli** [tomasortiz9598/macowins#1]
Hola Tomás,

Nos comentaste por el formulario que tenés el siguiente error: 

```
Como hago para correr los tests? ya probe mvn test pero me tira:

-------------------------------------------------------
 T E S T S



                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
--------at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Exceptioat java.base/java.lang.reflect.Method.invoke(Method.java:566)n
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
        at org.jacoco.agent.rt.internal_6da5971.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)
        at org.jacoco.agent.rt.internal_6da5971.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)
        at org.jacoco.agent.rt.internal_6da5971.PreMain.createRuntime(PreMain.java:55)
        at org.jacoco.agent.rt.internal_6da5971.PreMain.premain(PreMain.java:47)
        ... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
        at java.base/java.lang.Class.getField(Class.java:1999)
        at org.jacoco.agent.rt.internal_6da5971.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)
        ... 9 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
Aborted (core dumped)

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.356 s
[INFO] Finished at: 2021-04-16T15:59:12-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project ejercicio: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

```

Sin embargo este error no me ocurre. ¿Qué versión de Java tenés? Sospecho que tenés una versión diferente (tiene que ser JDK 8, por ahora no soportamos otras versiones). 

Por otro lado, tus tests tiene que ser públicos. Por ejemplo vos tenés: https://github.com/tomasortiz9598/macowins/blob/d9d35a02be875eca874b824623df570cfe1cf8e8/src/test/java/VentasTest.java#L14. Tendrías que agregarle el modificador `public`  a la declaración de la clase.

**Comment by tomasortiz9598** [comment]
Hola Franco, muchas gracias por tu respuesta.

En cuanto al modificador public ya subi la modificacion.

Veo que venia usando la version 11 de java. Igualmente al instalar la version 8, cuando hago java -version me sigue tirando que esta en la 11.

tomasortiz@it-ThinkPad-T14-Gen-1:~/Facultad/DDS/java-base-project-main$ sudo apt install openjdk-8-jdk
Reading package lists... Done
Building dependency tree       
Reading state information... Done
openjdk-8-jdk is already the newest version (8u282-b08-0ubuntu1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 25 not upgraded.
tomasortiz@it-ThinkPad-T14-Gen-1:~/Facultad/DDS/java-base-project-main$ java -version
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.18.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode)

**Comment by tomasortiz9598** [comment]
Ahi pude apuntar a la versión 8 de java.

Un update-alternatives lo arreglo.

Gracias

**Comment by tomasortiz9598** [comment]
Igualmente todos los tests me estan tirando NullPointerException.

Por que puede ser?

**Comment by tomasortiz9598** [comment]
Cierro issue. Ya encontre la solucion
